let DataRuko = [
  {
    id: 1,
    imageUrl: "/images/ruko/ruko1.jpeg",
    title: "DISEWAKAN Apartemen La Maison 3BR, Barito, Jakarta Selatan",
    alamat: "Alamat :Jl. Barito II No.56, Kebayoran Baru",
    provinsi: "Provinsi : Jawa Barat",
    ukuran: "Ukuran : 7 X 5",
    harga: "Harga : Rp25.000.000 / thn",
    pemilik: "Pemilik : Suryadi",
    whatsapp: "Whatsapp : 082156721635",
  },
  {
    id: 2,
    imageUrl: "/images/ruko/ruko2.jpeg",
    title: "DISEWAKAN Ruko Strategis 4 Lantai di Surabaya!",
    alamat: "Alamat : Jl. Joglo Raya No 15, Joglo",
    provinsi: "Provinsi : Jawa Timur",
    ukuran: "Ukuran : 7 X 5",
    harga: "Harga : Rp34,000,000 / thn",
    pemilik: "Pemilik : Rosa Rahmadi", 
    whatsapp: "Whatsapp : 081925637182",
  },
  {
    id: 3,
    imageUrl: "/images/ruko/ruko3.png",
    title: "Ruko siap pakai disewakan di muara karang!",
    alamat: "Alamat : Muara Karang, Jakarta Utara",
    provinsi: "Provinsi : Jawa Barat",
    ukuran: "Ukuran : 7 X 5",
    harga: "Harga : Rp35.000.000 / thn",
    pemilik: "Pemilik : Vina Risma", 
    whatsapp: "Whatsapp : 081276110024",
  },
  {
    id: 4,
    imageUrl: "/images/ruko/ruko5.jpeg",
    title: "SEWA CEPAT RUKO BARU SIAP HUNI HARGA RUGI The Savia @ Bumi Serpong Damai",
    alamat: "Alamat : Serpong, Tangerang, Banten",
    provinsi: "Provinsi : Jawa Barat",
    ukuran: "Ukuran : 7 X 5",
    harga: "Harga : Rp34.000.000 / thn",
    pemilik: "Pemilik : Bahrul", 
    whatsapp: "Whatsapp : 083671000265",
  },
  {
    id: 5,
    imageUrl: "/images/ruko/ruko3.png",
    title: "Ruko siap pakai disewakan di Sumenep!",
    alamat: "Alamat : Sumenep, Madura, Jawatimur",
    provinsi: "Provinsi : Jawa Timur",
    ukuran: "Ukuran : 7 X 5",
    harga: "Harga : Rp20.000.000 / thn",
    pemilik: "Pemilik : Iwan Setiawan", 
    whatsapp: "Whatsapp : 085788546712",
  },
  {
    id: 6,
    imageUrl: "/images/ruko/ruko4.jpeg",
    title: "Disewakan Kost Perumahan",
    alamat: "Alamat : malang",
    provinsi: "Provinsi : Jawa Timur",
    ukuran: "Ukuran : 7 X 5",
    harga: "Harga : Rp1.000.000/ bulan",
    pemilik: "Pemilik : Wanto", 
    whatsapp: "Whatsapp : 085814526716",
  },
  {
    id: 7,
    imageUrl: "/images/ruko/ruko8.png",
    title: "RUKO ERLY, GADING SERPONG,TANGGERANG",
    alamat: "Alamat : Sumenep",
    provinsi: "Provinsi : Jawa Barat",
    ukuran: "Ukuran : 7 X 5",
    harga: "Harga : 35.000.000/ thn",
    pemilik: "Pemilik : Citra Rasya", 
    whatsapp: "Whatsapp : 081211218790",
  },
  {
    id: 8,
    imageUrl: "/images/ruko/ruko9.png",
    title: "Disewakan Ruko Shibuya, Purwokerto Banyumas",
    alamat: "Alamat : Purwokerto, Banyumas",
    provinsi: "Provinsi : Jawa Tengah",
    ukuran: "Ukuran : 7 X 5",
    harga: "Harga : Rp120 jt/ bulan",
    pemilik: "Pemilik : Aminah", 
    whatsapp: "Whatsapp : 087754641346",
  },

]
 
function getDataRuko() {
  return DataRuko;
}
  
export { getDataRuko };